name: Node.js CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm run eslint

      - name: Run Jest
        run: pnpm run test

      - name: Run Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{secrets.CHROMATIC_PROJECT_TOKEN}}
