name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '18.x'
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn eslint

      - name: Run Jest
        run: yarn test --collectCoverage --silent

#      - name: Run Chromatic
#        uses: chromaui/action@v1
#        with:
#          projectToken: ${{secrets.CHROMATIC_PROJECT_TOKEN}}
#        env:
#          NODE_OPTIONS: "--max-old-space-size=15360 --openssl-legacy-provider"
